---
# Copyright (C) 2023 The ORT Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

name: 'Install ScanCode'
description: 'Install ScanCode via Python package install (pip).'
author: 'The ORT Project Authors'

inputs:
  scancode-version:
    default: '31.2.1'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup ScanCode Toolkit
      id: setup-scancode-toolkit
      shell: bash
      env:
        SCANCODE_VERSION: ${{ inputs.scancode-version }}
      run: |
        echo -e "\e[1;33m Setup ScanCode Toolkit version ${SCANCODE_VERSION}..."
        curl -Os https://raw.githubusercontent.com/nexB/scancode-toolkit/v$SCANCODE_VERSION/requirements.txt
        # Use option --use-pep517 to silence a warning for the packages 'future' and 'pefile', see
        # also https://github.com/pypa/pip/issues/8559.
        pip install --use-pep517 -q -U --constraint requirements.txt scancode-toolkit==$SCANCODE_VERSION
        rm requirements.txt
        printenv >> "$GITHUB_ENV"
        scancode --version
