---
# Copyright (C) 2022 The ORT Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

name: 'Shallow clone ort-config repository'
description: 'Shallow clone ort-config repository if ORT_CONFIG_PATH environment var is empty.'
author: 'The ORT Project Authors'

inputs:
  ort-config-path:
    default: ''
    description: |
      Path to ORT configuration directory.
  ort-config-repository:
    default: 'https://github.com/oss-review-toolkit/ort-config.git'
    description: |
      URL to ORT configuration repository to use.
    required: false
  ort-config-revision:
    default: 'main'
    description: |
      The Git revision or branch of the ORT configuration repository to use.
    required: false

runs:
  using: 'composite'
  steps:
    - name: Shallow clone ort-config repository if ORT_CONFIG_PATH is empty
      id: ort-config
      shell: bash
      env:
        ORT_CONFIG_PATH: ${{ inputs.ort-config-path }}
        ORT_CONFIG_VCS_URL: ${{ inputs.ort-config-repository }}
        ORT_CONFIG_VCS_REVISION: ${{ inputs.ort-config-revision }}
      run: |
        if [[ -z "$(ls -A ${ORT_CONFIG_PATH})" ]]; then
          # Using bash instead of actions/checkout as we need to capture Git revision of ort-config
          ORT_CONFIG_VCS_REVISION=${ORT_CONFIG_VCS_REVISION:-$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')}
          echo -e "\e[1;33m Retrieving ORT config ORT from ${ORT_CONFIG_VCS_URL}... "
          cd $ORT_CONFIG_PATH
          git init -q
          git remote add origin $ORT_CONFIG_VCS_URL
          git fetch -q --depth 1 origin $ORT_CONFIG_VCS_REVISION

          git checkout -q FETCH_HEAD
        fi
    - name: Capture ORT config URL and revision
      id: ort-config-url-and-revision
      shell: bash
      env:
        ORT_CONFIG_PATH: ${{ inputs.ort-config-path }}
      run: |
        cd $ORT_CONFIG_PATH
        export ORT_CONFIG_VCS_URL=$(git config remote.origin.url)
        export ORT_CONFIG_VCS_REVISION=$(git rev-parse HEAD)
        echo "ORT_CONFIG_VCS_URL: ${ORT_CONFIG_VCS_URL}"
        echo "ORT_CONFIG_VCS_REVISION: ${ORT_CONFIG_VCS_REVISION}"
        printenv >> "$GITHUB_ENV"
