name: Build and upload ORT

on: 
  workflow_dispatch:

jobs:
  ort:
    runs-on: ubuntu-latest
    name: Build and upload ORT
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build ORT
        id: ort-build
        shell: bash
        env:
          ORT_REVISION: ${{ inputs.ort-revision }}
        run: |
          echo -e "\e[1;33m Building ORT..."
          cd $GITHUB_WORKSPACE
          git clone https://github.com/oss-review-toolkit/ort.git
          cd ort
          GIT_REVISION=$(git describe --abbrev=10 --always --tags --dirty --match=[0-9]*)
          ./gradlew --no-daemon --stacktrace -Pversion="${GIT_REVISION}" cli:installShadowDist
          mv cli/build/install/cli-shadow/lib/*.jar $GITHUB_WORKSPACE/ort.jar
          echo -e "\e[1;33m Built ORT version '$(java -jar ${GITHUB_WORKSPACE}/ort.jar --version)'."
      - name: Upload ORT fatJar
        uses: actions/upload-artifact@v3
        with:
          name: "ort-compiled"
          path: ${{ github.workspace }}/ort.jar
          if-no-files-found: warn
