name: Scan Influx Client

on: 
  workflow_dispatch:

jobs:
  ort:
    runs-on: ubuntu-latest
    name: Run ORT
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: 'influxdata/influxdb-client-go'
          ref: 'v2.12.1'
      - name: Run GitHub Action for ORT
        uses: tsteenbe/ort-ci-github-action/no-docker@pr-6225
        with:
          http-file-server-url: ${{ secrets.ARTIFACTORY_URL }}
          http-file-server-token: ${{ secrets.ARTIFACTORY_TOKEN }}
          ort-config-repository: 'https://github.com/tsteenbe/ort-config'
          run: >
            cache-dependencies,
            labels,
            analyzer,
            evaluator,
            advisor,
            reporter,
            upload-results
      - name: Print some folders in ~/go
        run: |
          echo -e "\e[1;33m $HOME/go/pkg/mod/cache/download/github.com"
          ls -all $HOME/go/pkg/mod/cache/download/github.com || :
