name: Scan Influx Client

on: 
  workflow_dispatch:

jobs:
  ort:
    runs-on: ubuntu-latest
    name: Run ORT
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: 'influxdata/influxdb-client-go'
          ref: 'v2.12.1'
      - name: Run GitHub Action for ORT
        uses: tsteenbe/ort-ci-github-action@pr-6225-experimental
        with:
          run: 'debug'
      - name: Print some folders in ~/.go
        run: |
          echo -e "\e[1;33m $HOME/go/pkg/mod/cache/download/github.com"
          ls -all $HOME/go/pkg/mod/cache/download/github.com || :
